#ifndef _TABLE_CMD_
#define _TABLE_CMD_

#include <string>

using namespace std;
const string CREATE_PLAYER_CMD = "CREATE TABLE PLAYER(" \
    "PLAYER_ID SERIAL NOT NULL," \
    "TEAM_ID SERIAL NOT NULL," \
    "UNIFORM_NUM INT NOT NULL," \
    "FIRST_NAME TEXT NOT NULL," \
    "LAST_NAME TEXT NOT NULL," \
	  "MPG INT NOT NULL," \
	  "PPG INT NOT NULL," \
	  "RPG INT NOT NULL," \
	  "APG INT NOT NULL," \
	  "SPG DECIMAL(4,1) NOT NULL," \
	  "BPG DECIMAL(4,1) NOT NULL," \
    "PRIMARY KEY (PLAYER_ID)," \
    "FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE);";

const string CREATE_TEAM_CMD = "CREATE TABLE TEAM(" \
    "TEAM_ID SERIAL NOT NULL," \
    "NAME TEXT NOT NULL," \
	  "STATE_ID SERIAL NOT NULL," \
	  "COLOR_ID SERIAL NOT NULL," \
	  "WINS INT NOT NULL," \
	  "LOSSES INT NOT NULL," \
    "PRIMARY KEY (TEAM_ID)," \
    "FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE," \
    "FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE);";
    
const string CREATE_STATE_CMD = "CREATE TABLE STATE(" \
    "STATE_ID SERIAL NOT NULL," \
    "NAME TEXT NOT NULL," \
    "PRIMARY KEY (STATE_ID));";

const string CREATE_COLOR_CMD = "CREATE TABLE COLOR(" \
    "COLOR_ID SERIAL NOT NULL," \
    "NAME TEXT NOT NULL," \
    "PRIMARY KEY (COLOR_ID));";

#endif //_TABLE_CMD
